name: Sync Posts

on:
  push:
    paths:
      - 'ObsidianVault/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Vercel API
        shell: pwsh
        run: |
          $baseUrl = "${{ secrets.VERCEL_SYNC_URL }}"
          $baseUrl = $baseUrl.Trim()
          $baseUrl = $baseUrl -replace "^https?://", ""
          $uri = "https://" + $baseUrl
          
          Write-Host "Base URL: $baseUrl"
          Write-Host "Final URI: $uri/api/sync"
          
          try {
            $response = Invoke-RestMethod `
              -Method POST `
              -Uri "$uri/api/sync" `
              -Headers @{
                "Authorization" = "Bearer ${{ secrets.SYNC_SECRET_TOKEN }}"
              } `
              -ErrorAction Stop
            
            Write-Host "Response: $response"
            Write-Host "Sync successful!"
          }
          catch {
            Write-Error "Sync failed: $_"
            exit 1
          } 