name: Sync Posts

on:
  push:
    branches:
      - main
    paths:
      - 'ObsidianVault/posts/**'

permissions:
  contents: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Sync posts
        run: npm run sync-posts
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/posts/
          git commit -m "Sync posts from Obsidian" || echo "No changes to commit"
          git push 