name: Sync Posts

on:
  push:
    branches:
      - main
    paths:
      - 'ObsidianVault/posts/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Pull latest changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main --rebase
          
      - name: Sync posts
        run: |
          node scripts/sync-posts.js
          
      - name: Debug directory contents
        run: |
          echo "Contents of public/posts:"
          ls -la public/posts/
          echo "Contents of ObsidianVault/posts:"
          ls -la ObsidianVault/posts/OrhanBiler.us/
        
      - name: Commit and push if changed
        run: |
          git add public/posts/
          git status
          git commit -m "Sync posts from Obsidian" || echo "No changes to commit"
          git push origin main
          
      - name: Deploy to Vercel
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          if [ -n "$VERCEL_DEPLOY_HOOK" ]; then
            curl -X POST "$VERCEL_DEPLOY_HOOK"
            echo "Triggered Vercel deployment"
          else
            echo "No Vercel deploy hook configured"
            echo "Please add VERCEL_DEPLOY_HOOK secret in repository settings"
          fi 