name: Sync Posts

on:
  push:
    branches:
      - main
    paths:
      - 'ObsidianVault/posts/OrhanBiler.us/**'  # Only trigger on changes to posts
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run sync script
        run: |
          echo "Running sync script..."
          npm run sync-posts
          echo "Sync completed"

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/posts/
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: sync blog posts" && git push)

      - name: Deploy to Vercel
        if: success()
        run: |
          echo "Triggering Vercel deployment..."
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{"target": "production"}'
          
          echo "Waiting for deployment to propagate..."
          sleep 30 