name: Sync Posts

on:
  push:
    branches:
      - main
    paths:
      - 'ObsidianVault/posts/**'
      - 'ObsidianVault/posts/OrhanBiler.us/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Pull latest changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main --rebase
          
      - name: Sync posts
        run: |
          node scripts/sync-posts.js
        
      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain public/posts/ | wc -l | xargs -I {} echo "changes={}" >> $GITHUB_OUTPUT
        
      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes != '0'
        run: |
          git add public/posts/
          git commit -m "Sync posts from Obsidian [skip ci]"
          git push origin main
          
      - name: Deploy to Vercel
        if: success()
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          if [ -n "$VERCEL_DEPLOY_HOOK" ]; then
            curl -X POST "$VERCEL_DEPLOY_HOOK"
          else
            echo "No Vercel deploy hook configured"
          fi 