name: Sync Posts

on:
  push:
    branches:
      - main
    paths:
      - 'ObsidianVault/posts/**'
  workflow_dispatch:  # Allows manual triggering if needed

permissions:
  contents: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper sync
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Pull latest changes
        run: |
          git pull origin main --rebase
          
      - name: Sync posts
        run: npm run sync-posts
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/posts/
          git commit -m "Sync posts from Obsidian" || echo "No changes to commit"
          git push origin main --force
          
      - name: Deploy to Vercel
        if: success()
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_qTDmVvZwQWTkd35j89cYQMbYmV0Y/QO4NBCxluB" 